### ISSUE TITLE
Improve labelling

### ISSUE THREAD

**Issue by Schpidi** [EOX-A/d3.TimeSlider#21]
Sometimes it's difficult to correctly interpret the labels. Right now the start of time periods are labelled. I'd propose to investigate labelling periods instead maybe using some sort of a dashed background.

**Comment by pacesm** [comment]
@Schpidi  do you mean something like the time-selection implemented by @santilland in VirES?

Looking at the vires.services I would add two additional requirements:
* the time-slider should use by default a locale neutral date/time format,
* the date/time format should be configurable in order to make the labels consistent with the rest of the UI.

**Comment by Schpidi** [comment]
@pacesm labelling the selection during selection as done in VirES is a good thing. What I was referring to are the labels that are always visible at the bottom.

**Comment by santilland** [comment]
Solved in #18
